apiVersion: v1
kind: Service
metadata:
  name: java-registration-service
spec:
  selector:
    app: java-registration-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
